FROM debian:buster-slim

ENV LGUID 65534
ENV LGGID 65534

EXPOSE 8000

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y \
    python-flask \
    traceroute \
    netbase \
    gunicorn

WORKDIR /bird-lg

ADD lgproxy.* /bird-lg/
ADD bird.py /bird-lg/
ADD entrypoint.sh /entrypoint.sh

RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
CMD ["lgproxy:app"]